/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\ComparatoreGE" *)
(* src = "structural/components.v:39.1-45.10" *)
module \$paramod\ComparatoreGE\N=s32'00000000000000000000000000000110 (A, B, O);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "structural/components.v:40.19-40.20" *)
  input [5:0] A;
  wire [5:0] A;
  (* src = "structural/components.v:41.19-41.20" *)
  input [5:0] B;
  wire [5:0] B;
  (* src = "structural/components.v:42.12-42.13" *)
  output O;
  wire O;
  assign _00_ = A[5] | ~(B[5]);
  assign _01_ = B[5] | ~(A[5]);
  assign _02_ = A[4] | ~(B[4]);
  assign _03_ = B[4] | ~(A[4]);
  assign _04_ = A[3] | ~(B[3]);
  assign _05_ = B[3] | ~(A[3]);
  assign _06_ = A[2] | ~(B[2]);
  assign _07_ = B[2] | ~(A[2]);
  assign _08_ = A[1] | ~(B[1]);
  assign _09_ = B[0] & ~(A[0]);
  assign _10_ = B[1] | ~(A[1]);
  assign _11_ = ~(_09_ & _10_);
  assign _12_ = ~(_08_ & _11_);
  assign _13_ = ~(_07_ & _12_);
  assign _14_ = ~(_06_ & _13_);
  assign _15_ = ~(_05_ & _14_);
  assign _16_ = ~(_04_ & _15_);
  assign _17_ = ~(_03_ & _16_);
  assign _18_ = ~(_02_ & _17_);
  assign _19_ = ~(_01_ & _18_);
  assign O = _00_ & _19_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\Mux4" *)
(* src = "structural/components.v:67.1-81.10" *)
module \$paramod\Mux4\N=s32'00000000000000000000000000000110 (In0, In1, In2, In3, sel, O);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  (* src = "structural/components.v:68.19-68.22" *)
  input [5:0] In0;
  wire [5:0] In0;
  (* src = "structural/components.v:68.24-68.27" *)
  input [5:0] In1;
  wire [5:0] In1;
  (* src = "structural/components.v:68.29-68.32" *)
  input [5:0] In2;
  wire [5:0] In2;
  (* src = "structural/components.v:68.34-68.37" *)
  input [5:0] In3;
  wire [5:0] In3;
  (* src = "structural/components.v:70.24-70.25" *)
  output [5:0] O;
  wire [5:0] O;
  (* src = "structural/components.v:69.17-69.20" *)
  input [1:0] sel;
  wire [1:0] sel;
  assign _00_ = ~(sel[0] | sel[1]);
  assign _01_ = ~(In0[4] & _00_);
  assign _02_ = sel[0] & sel[1];
  assign _03_ = ~(In3[4] & _02_);
  assign _04_ = _01_ & _03_;
  assign _05_ = sel[0] & ~(sel[1]);
  assign _06_ = ~(In1[4] & _05_);
  assign _07_ = sel[1] & ~(sel[0]);
  assign _08_ = ~(In2[4] & _07_);
  assign _09_ = _06_ & _08_;
  assign O[4] = ~(_04_ & _09_);
  assign _10_ = ~(In0[3] & _00_);
  assign _11_ = ~(In3[3] & _02_);
  assign _12_ = _10_ & _11_;
  assign _13_ = ~(In1[3] & _05_);
  assign _14_ = ~(In2[3] & _07_);
  assign _15_ = _13_ & _14_;
  assign O[3] = ~(_12_ & _15_);
  assign _16_ = ~(In0[2] & _00_);
  assign _17_ = ~(In3[2] & _02_);
  assign _18_ = _16_ & _17_;
  assign _19_ = ~(In1[2] & _05_);
  assign _20_ = ~(In2[2] & _07_);
  assign _21_ = _19_ & _20_;
  assign O[2] = ~(_18_ & _21_);
  assign _22_ = ~(In0[1] & _00_);
  assign _23_ = ~(In3[1] & _02_);
  assign _24_ = _22_ & _23_;
  assign _25_ = ~(In1[1] & _05_);
  assign _26_ = ~(In2[1] & _07_);
  assign _27_ = _25_ & _26_;
  assign O[1] = ~(_24_ & _27_);
  assign _28_ = ~(In0[0] & _00_);
  assign _29_ = ~(In3[0] & _02_);
  assign _30_ = _28_ & _29_;
  assign _31_ = ~(In1[0] & _05_);
  assign _32_ = ~(In2[0] & _07_);
  assign _33_ = _31_ & _32_;
  assign O[0] = ~(_30_ & _33_);
  assign _34_ = ~(In0[5] & _00_);
  assign _35_ = ~(In3[5] & _02_);
  assign _36_ = _34_ & _35_;
  assign _37_ = ~(In1[5] & _05_);
  assign _38_ = ~(In2[5] & _07_);
  assign _39_ = _37_ & _38_;
  assign O[5] = ~(_36_ & _39_);
endmodule

(* dynports =  1  *)
(* hdlname = "\\RegistroPP" *)
(* src = "structural/components.v:6.1-17.10" *)
module \$paramod\RegistroPP\N=s32'00000000000000000000000000000001 (clk, rst, enable, D, Q);
  (* src = "structural/components.v:10.19-10.20" *)
  input D;
  wire D;
  (* src = "structural/components.v:11.24-11.25" *)
  output Q;
  reg Q;
  (* src = "structural/components.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "structural/components.v:9.11-9.17" *)
  input enable;
  wire enable;
  (* src = "structural/components.v:8.11-8.14" *)
  input rst;
  wire rst;
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q <= 1'h0;
    else if (enable) Q <= D;
endmodule

(* dynports =  1  *)
(* hdlname = "\\RegistroPP" *)
(* src = "structural/components.v:6.1-17.10" *)
module \$paramod\RegistroPP\N=s32'00000000000000000000000000000010 (clk, rst, enable, D, Q);
  (* src = "structural/components.v:10.19-10.20" *)
  input [1:0] D;
  wire [1:0] D;
  (* src = "structural/components.v:11.24-11.25" *)
  output [1:0] Q;
  reg [1:0] Q;
  (* src = "structural/components.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "structural/components.v:9.11-9.17" *)
  input enable;
  wire enable;
  (* src = "structural/components.v:8.11-8.14" *)
  input rst;
  wire rst;
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else if (enable) Q[0] <= D[0];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else if (enable) Q[1] <= D[1];
endmodule

(* dynports =  1  *)
(* hdlname = "\\RegistroPP" *)
(* src = "structural/components.v:6.1-17.10" *)
module \$paramod\RegistroPP\N=s32'00000000000000000000000000000110 (clk, rst, enable, D, Q);
  (* src = "structural/components.v:10.19-10.20" *)
  input [5:0] D;
  wire [5:0] D;
  (* src = "structural/components.v:11.24-11.25" *)
  output [5:0] Q;
  reg [5:0] Q;
  (* src = "structural/components.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "structural/components.v:9.11-9.17" *)
  input enable;
  wire enable;
  (* src = "structural/components.v:8.11-8.14" *)
  input rst;
  wire rst;
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else if (enable) Q[0] <= D[0];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else if (enable) Q[1] <= D[1];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[2] <= 1'h0;
    else if (enable) Q[2] <= D[2];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[3] <= 1'h0;
    else if (enable) Q[3] <= D[3];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[4] <= 1'h0;
    else if (enable) Q[4] <= D[4];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[5] <= 1'h0;
    else if (enable) Q[5] <= D[5];
endmodule

(* dynports =  1  *)
(* hdlname = "\\RegistroPP" *)
(* src = "structural/components.v:6.1-17.10" *)
module \$paramod\RegistroPP\N=s32'00000000000000000000000000001010 (clk, rst, enable, D, Q);
  (* src = "structural/components.v:10.19-10.20" *)
  input [9:0] D;
  wire [9:0] D;
  (* src = "structural/components.v:11.24-11.25" *)
  output [9:0] Q;
  reg [9:0] Q;
  (* src = "structural/components.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "structural/components.v:9.11-9.17" *)
  input enable;
  wire enable;
  (* src = "structural/components.v:8.11-8.14" *)
  input rst;
  wire rst;
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[0] <= 1'h0;
    else if (enable) Q[0] <= D[0];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[1] <= 1'h0;
    else if (enable) Q[1] <= D[1];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[2] <= 1'h0;
    else if (enable) Q[2] <= D[2];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[3] <= 1'h0;
    else if (enable) Q[3] <= D[3];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[4] <= 1'h0;
    else if (enable) Q[4] <= D[4];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[5] <= 1'h0;
    else if (enable) Q[5] <= D[5];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[6] <= 1'h0;
    else if (enable) Q[6] <= D[6];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[7] <= 1'h0;
    else if (enable) Q[7] <= D[7];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[8] <= 1'h0;
    else if (enable) Q[8] <= D[8];
  (* src = "structural/components.v:13.5-16.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) Q[9] <= 1'h0;
    else if (enable) Q[9] <= D[9];
endmodule

(* src = "structural/vending_fsm.v:3.1-174.10" *)
module vending_fsm(clk, rst, coin, selezione, conferma, annulla, is_credito_suff, is_stock_ok, mode_init, init_counter, clear_outputs, do_add_coin, do_cancel, do_err, do_ok, do_erogazione, sel_latched, prodotto1, prodotto2, prodotto3, prodotto4
);
  (* src = "structural/vending_fsm.v:74.22-74.43" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "structural/vending_fsm.v:10.23-10.30" *)
  input annulla;
  wire annulla;
  (* src = "structural/vending_fsm.v:21.23-21.36" *)
  output clear_outputs;
  wire clear_outputs;
  (* src = "structural/vending_fsm.v:4.23-4.26" *)
  input clk;
  wire clk;
  (* src = "structural/vending_fsm.v:7.23-7.27" *)
  input [2:0] coin;
  wire [2:0] coin;
  (* src = "structural/vending_fsm.v:9.23-9.31" *)
  input conferma;
  wire conferma;
  (* src = "structural/vending_fsm.v:24.23-24.34" *)
  output do_add_coin;
  wire do_add_coin;
  (* src = "structural/vending_fsm.v:25.23-25.32" *)
  output do_cancel;
  wire do_cancel;
  (* src = "structural/vending_fsm.v:28.23-28.36" *)
  output do_erogazione;
  wire do_erogazione;
  (* src = "structural/vending_fsm.v:26.23-26.29" *)
  output do_err;
  wire do_err;
  (* src = "structural/vending_fsm.v:27.23-27.28" *)
  output do_ok;
  wire do_ok;
  (* src = "structural/vending_fsm.v:18.23-18.35" *)
  output [3:0] init_counter;
  reg [3:0] init_counter;
  (* src = "structural/vending_fsm.v:13.23-13.38" *)
  input is_credito_suff;
  wire is_credito_suff;
  (* src = "structural/vending_fsm.v:14.23-14.34" *)
  input is_stock_ok;
  wire is_stock_ok;
  (* src = "structural/vending_fsm.v:17.23-17.32" *)
  output mode_init;
  wire mode_init;
  (* src = "structural/vending_fsm.v:47.22-47.32" *)
  wire [1:0] next_stato;
  (* src = "structural/vending_fsm.v:34.23-34.32" *)
  output prodotto1;
  wire prodotto1;
  (* src = "structural/vending_fsm.v:35.23-35.32" *)
  output prodotto2;
  wire prodotto2;
  (* src = "structural/vending_fsm.v:36.23-36.32" *)
  output prodotto3;
  wire prodotto3;
  (* src = "structural/vending_fsm.v:37.23-37.32" *)
  output prodotto4;
  wire prodotto4;
  (* src = "structural/vending_fsm.v:5.23-5.26" *)
  input rst;
  wire rst;
  (* src = "structural/vending_fsm.v:31.23-31.34" *)
  output [2:0] sel_latched;
  reg [2:0] sel_latched;
  (* src = "structural/vending_fsm.v:8.23-8.32" *)
  input [2:0] selezione;
  wire [2:0] selezione;
  (* src = "structural/vending_fsm.v:47.15-47.20" *)
  reg [1:0] stato;
  assign mode_init = ~(stato[0] | stato[1]);
  assign _01_ = ~(coin[0] | coin[1]);
  assign _02_ = _01_ & ~(coin[2]);
  assign _03_ = _02_ & ~(annulla);
  assign _04_ = conferma & _03_;
  assign _05_ = annulla | _04_;
  assign _06_ = stato[1] & ~(stato[0]);
  assign _07_ = ~(_05_ & _06_);
  assign _08_ = ~(annulla | _02_);
  assign _09_ = stato[0] & ~(stato[1]);
  assign _10_ = ~(_08_ & _09_);
  assign _11_ = init_counter[3] & ~(init_counter[2]);
  assign _12_ = init_counter[1] & init_counter[0];
  assign _13_ = _11_ & ~(stato[1]);
  assign _14_ = _12_ & _13_;
  assign _15_ = stato[0] | _14_;
  assign _16_ = ~(_10_ & _15_);
  assign next_stato[0] = ~(_07_ & _16_);
  assign _17_ = init_counter[2] | _12_;
  assign _18_ = init_counter[2] & _12_;
  assign _19_ = ~(init_counter[3] | _18_);
  assign _35_ = _17_ & _19_;
  assign _20_ = ~(init_counter[2] & init_counter[3]);
  assign _21_ = init_counter[1] ^ init_counter[0];
  assign _34_ = _20_ & _21_;
  assign _22_ = init_counter[3] & _17_;
  assign _33_ = ~(init_counter[0] | _22_);
  assign _23_ = _06_ | _09_;
  assign do_add_coin = _08_ & _23_;
  assign do_cancel = annulla & _23_;
  assign _24_ = selezione[2] & is_credito_suff;
  assign _25_ = ~(is_stock_ok & _24_);
  assign _26_ = conferma & _02_;
  assign _27_ = _25_ & _26_;
  assign _28_ = _06_ & ~(annulla);
  assign do_err = _27_ & _28_;
  assign _29_ = _06_ & ~(_25_);
  assign do_ok = _04_ & _29_;
  assign do_erogazione = stato[0] & stato[1];
  assign _30_ = do_ok & ~(selezione[1]);
  assign prodotto1 = _30_ & ~(selezione[0]);
  assign prodotto2 = selezione[0] & _30_;
  assign _31_ = selezione[1] & do_ok;
  assign prodotto3 = _31_ & ~(selezione[0]);
  assign prodotto4 = selezione[0] & _31_;
  assign _32_ = _27_ | ~(_28_);
  assign next_stato[1] = ~(_10_ & _32_);
  assign _00_ = conferma & selezione[2];
  assign _36_ = ~(_19_ | _22_);
  (* src = "structural/vending_fsm.v:57.5-68.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) init_counter[0] <= 1'h0;
    else if (mode_init) init_counter[0] <= _33_;
  (* src = "structural/vending_fsm.v:57.5-68.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) init_counter[1] <= 1'h0;
    else if (mode_init) init_counter[1] <= _34_;
  (* src = "structural/vending_fsm.v:57.5-68.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) init_counter[2] <= 1'h0;
    else if (mode_init) init_counter[2] <= _35_;
  (* src = "structural/vending_fsm.v:57.5-68.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) init_counter[3] <= 1'h0;
    else if (mode_init) init_counter[3] <= _36_;
  (* src = "structural/vending_fsm.v:71.5-77.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) sel_latched[0] <= 1'h0;
    else if (_00_) sel_latched[0] <= selezione[0];
  (* src = "structural/vending_fsm.v:71.5-77.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) sel_latched[1] <= 1'h0;
    else if (_00_) sel_latched[1] <= selezione[1];
  (* src = "structural/vending_fsm.v:71.5-77.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) sel_latched[2] <= 1'h0;
    else if (_00_) sel_latched[2] <= selezione[2];
  (* src = "structural/vending_fsm.v:57.5-68.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) stato[0] <= 1'h0;
    else stato[0] <= next_stato[0];
  (* src = "structural/vending_fsm.v:57.5-68.8" *)
  always @(posedge clk, negedge rst)
    if (!rst) stato[1] <= 1'h0;
    else stato[1] <= next_stato[1];
  assign clear_outputs = stato[0];
endmodule

(* top =  1  *)
(* src = "structural/vending_structural.v:4.1-307.10" *)
module vending_structural(clk, rst, coin, selezione, conferma, annulla, credito, prodotto1, prodotto2, prodotto3, prodotto4, errore, resto, disponibile, coin_01, coin_02, coin_05, coin_10);
  (* src = "structural/vending_structural.v:107.22-107.34" *)
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  wire _0794_;
  wire _0795_;
  wire _0796_;
  wire _0797_;
  wire _0798_;
  wire _0799_;
  wire _0800_;
  wire _0801_;
  wire _0802_;
  wire _0803_;
  wire _0804_;
  wire _0805_;
  wire _0806_;
  wire _0807_;
  wire _0808_;
  wire _0809_;
  wire _0810_;
  wire _0811_;
  wire _0812_;
  wire _0813_;
  wire _0814_;
  (* src = "structural/vending_structural.v:10.23-10.30" *)
  input annulla;
  wire annulla;
  (* src = "structural/vending_structural.v:130.16-130.24" *)
  wire [5:0] c01_calc;
  (* src = "structural/vending_structural.v:129.16-129.24" *)
  wire [5:0] c02_calc;
  (* src = "structural/vending_structural.v:128.16-128.24" *)
  wire [5:0] c05_calc;
  (* src = "structural/vending_structural.v:127.16-127.24" *)
  wire [5:0] c10_calc;
  (* src = "structural/vending_structural.v:36.16-36.23" *)
  wire c_prod1;
  (* src = "structural/vending_structural.v:37.16-37.23" *)
  wire c_prod2;
  (* src = "structural/vending_structural.v:38.16-38.23" *)
  wire c_prod3;
  (* src = "structural/vending_structural.v:39.16-39.23" *)
  wire c_prod4;
  (* src = "structural/vending_structural.v:173.16-173.25" *)
  wire [5:0] cfg_value;
  (* src = "structural/vending_structural.v:174.16-174.28" *)
  wire [9:0] cfg_value_10;
  (* src = "structural/vending_structural.v:29.16-29.29" *)
  wire clear_outputs;
  (* src = "structural/vending_structural.v:5.23-5.26" *)
  input clk;
  wire clk;
  (* src = "structural/vending_structural.v:7.23-7.27" *)
  input [2:0] coin;
  wire [2:0] coin;
  (* src = "structural/vending_structural.v:253.16-253.24" *)
  wire [5:0] coin01_d;
  (* src = "structural/vending_structural.v:62.16-62.24" *)
  wire [5:0] coin01_q;
  (* src = "structural/vending_structural.v:254.16-254.24" *)
  wire [5:0] coin02_d;
  (* src = "structural/vending_structural.v:63.16-63.24" *)
  wire [5:0] coin02_q;
  (* src = "structural/vending_structural.v:255.16-255.24" *)
  wire [5:0] coin05_d;
  (* src = "structural/vending_structural.v:64.16-64.24" *)
  wire [5:0] coin05_q;
  (* src = "structural/vending_structural.v:256.16-256.24" *)
  wire [5:0] coin10_d;
  (* src = "structural/vending_structural.v:65.16-65.24" *)
  wire [5:0] coin10_q;
  (* src = "structural/vending_structural.v:21.23-21.30" *)
  output [5:0] coin_01;
  wire [5:0] coin_01;
  (* src = "structural/vending_structural.v:22.23-22.30" *)
  output [5:0] coin_02;
  wire [5:0] coin_02;
  (* src = "structural/vending_structural.v:23.23-23.30" *)
  output [5:0] coin_05;
  wire [5:0] coin_05;
  (* src = "structural/vending_structural.v:24.23-24.30" *)
  output [5:0] coin_10;
  wire [5:0] coin_10;
  (* src = "structural/vending_structural.v:180.16-180.29" *)
  (* unused_bits = "0 1 2 3 4 5" *)
  wire [9:0] coin_value_10;
  (* src = "structural/vending_structural.v:9.23-9.31" *)
  input conferma;
  wire conferma;
  (* src = "structural/vending_structural.v:12.23-12.30" *)
  output [5:0] credito;
  wire [5:0] credito;
  (* src = "structural/vending_structural.v:233.16-233.25" *)
  wire [5:0] credito_d;
  (* src = "structural/vending_structural.v:93.10-93.29" *)
  wire credito_ge_selprice;
  (* src = "structural/vending_structural.v:54.16-54.25" *)
  wire [5:0] credito_q;
  (* src = "structural/vending_structural.v:175.16-175.29" *)
  wire [9:0] disp_init_c01;
  (* src = "structural/vending_structural.v:19.23-19.34" *)
  output [9:0] disponibile;
  wire [9:0] disponibile;
  (* src = "structural/vending_structural.v:235.16-235.29" *)
  wire [9:0] disponibile_d;
  (* src = "structural/vending_structural.v:55.16-55.29" *)
  wire [9:0] disponibile_q;
  (* src = "structural/vending_structural.v:30.16-30.27" *)
  wire do_add_coin;
  (* src = "structural/vending_structural.v:31.16-31.25" *)
  wire do_cancel;
  (* src = "structural/vending_structural.v:34.16-34.29" *)
  (* unused_bits = "0" *)
  wire do_erogazione;
  (* src = "structural/vending_structural.v:32.16-32.22" *)
  wire do_err;
  (* src = "structural/vending_structural.v:33.16-33.21" *)
  wire do_ok;
  (* src = "structural/vending_structural.v:17.23-17.29" *)
  output [1:0] errore;
  wire [1:0] errore;
  (* src = "structural/vending_structural.v:244.16-244.24" *)
  wire [1:0] errore_d;
  (* src = "structural/vending_structural.v:56.16-56.24" *)
  wire [1:0] errore_q;
  (* src = "structural/vending_structural.v:28.16-28.30" *)
  wire [3:0] init_counter_w;
  (* src = "structural/vending_structural.v:184.10-184.23" *)
  wire init_price_p1;
  (* src = "structural/vending_structural.v:186.10-186.23" *)
  wire init_price_p2;
  (* src = "structural/vending_structural.v:188.10-188.23" *)
  wire init_price_p3;
  (* src = "structural/vending_structural.v:190.10-190.23" *)
  wire init_price_p4;
  (* src = "structural/vending_structural.v:27.16-27.25" *)
  wire mode_init;
  (* src = "structural/vending_structural.v:125.10-125.23" *)
  wire payout_active;
  (* src = "structural/vending_structural.v:124.16-124.29" *)
  wire [5:0] payout_amount;
  (* src = "structural/vending_structural.v:220.16-220.26" *)
  wire [5:0] price_p1_d;
  (* src = "structural/vending_structural.v:45.16-45.26" *)
  wire [5:0] price_p1_q;
  (* src = "structural/vending_structural.v:221.16-221.26" *)
  wire [5:0] price_p2_d;
  (* src = "structural/vending_structural.v:46.16-46.26" *)
  wire [5:0] price_p2_q;
  (* src = "structural/vending_structural.v:222.16-222.26" *)
  wire [5:0] price_p3_d;
  (* src = "structural/vending_structural.v:47.16-47.26" *)
  wire [5:0] price_p3_q;
  (* src = "structural/vending_structural.v:223.16-223.26" *)
  wire [5:0] price_p4_d;
  (* src = "structural/vending_structural.v:48.16-48.26" *)
  wire [5:0] price_p4_q;
  (* src = "structural/vending_structural.v:248.10-248.17" *)
  wire prod1_d;
  (* src = "structural/vending_structural.v:58.10-58.17" *)
  wire prod1_q;
  (* src = "structural/vending_structural.v:249.10-249.17" *)
  wire prod2_d;
  (* src = "structural/vending_structural.v:59.10-59.17" *)
  wire prod2_q;
  (* src = "structural/vending_structural.v:250.10-250.17" *)
  wire prod3_d;
  (* src = "structural/vending_structural.v:60.10-60.17" *)
  wire prod3_q;
  (* src = "structural/vending_structural.v:251.10-251.17" *)
  wire prod4_d;
  (* src = "structural/vending_structural.v:61.10-61.17" *)
  wire prod4_q;
  (* src = "structural/vending_structural.v:13.23-13.32" *)
  output prodotto1;
  wire prodotto1;
  (* src = "structural/vending_structural.v:14.23-14.32" *)
  output prodotto2;
  wire prodotto2;
  (* src = "structural/vending_structural.v:15.23-15.32" *)
  output prodotto3;
  wire prodotto3;
  (* src = "structural/vending_structural.v:16.23-16.32" *)
  output prodotto4;
  wire prodotto4;
  (* src = "structural/vending_structural.v:134.16-134.25" *)
  wire [5:0] qc01_next;
  (* src = "structural/vending_structural.v:133.16-133.25" *)
  wire [5:0] qc02_next;
  (* src = "structural/vending_structural.v:132.16-132.25" *)
  wire [5:0] qc05_next;
  (* src = "structural/vending_structural.v:131.16-131.25" *)
  wire [5:0] qc10_next;
  (* src = "structural/vending_structural.v:225.16-225.25" *)
  wire [5:0] qty_c01_d;
  (* src = "structural/vending_structural.v:49.16-49.25" *)
  wire [5:0] qty_c01_q;
  (* src = "structural/vending_structural.v:226.16-226.25" *)
  wire [5:0] qty_c02_d;
  (* src = "structural/vending_structural.v:50.16-50.25" *)
  wire [5:0] qty_c02_q;
  (* src = "structural/vending_structural.v:227.16-227.25" *)
  wire [5:0] qty_c05_d;
  (* src = "structural/vending_structural.v:51.16-51.25" *)
  wire [5:0] qty_c05_q;
  (* src = "structural/vending_structural.v:228.16-228.25" *)
  wire [5:0] qty_c10_d;
  (* src = "structural/vending_structural.v:52.16-52.25" *)
  wire [5:0] qty_c10_q;
  (* src = "structural/vending_structural.v:215.16-215.24" *)
  wire [5:0] qty_p1_d;
  (* src = "structural/vending_structural.v:41.16-41.24" *)
  wire [5:0] qty_p1_q;
  (* src = "structural/vending_structural.v:216.16-216.24" *)
  wire [5:0] qty_p2_d;
  (* src = "structural/vending_structural.v:42.16-42.24" *)
  wire [5:0] qty_p2_q;
  (* src = "structural/vending_structural.v:217.16-217.24" *)
  wire [5:0] qty_p3_d;
  (* src = "structural/vending_structural.v:43.16-43.24" *)
  wire [5:0] qty_p3_q;
  (* src = "structural/vending_structural.v:218.16-218.24" *)
  wire [5:0] qty_p4_d;
  (* src = "structural/vending_structural.v:44.16-44.24" *)
  wire [5:0] qty_p4_q;
  (* src = "structural/vending_structural.v:18.23-18.28" *)
  output [5:0] resto;
  wire [5:0] resto;
  (* src = "structural/vending_structural.v:246.16-246.23" *)
  wire [5:0] resto_d;
  (* src = "structural/vending_structural.v:57.16-57.23" *)
  wire [5:0] resto_q;
  (* src = "structural/vending_structural.v:6.23-6.26" *)
  input rst;
  wire rst;
  (* src = "structural/vending_structural.v:85.16-85.23" *)
  wire [1:0] sel_idx;
  (* src = "structural/vending_structural.v:35.16-35.27" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] sel_latched;
  (* src = "structural/vending_structural.v:87.16-87.25" *)
  wire [5:0] sel_price;
  (* src = "structural/vending_structural.v:88.16-88.23" *)
  wire [5:0] sel_qty;
  (* src = "structural/vending_structural.v:8.23-8.32" *)
  input [2:0] selezione;
  wire [2:0] selezione;
  (* src = "structural/vending_structural.v:266.10-266.16" *)
  wire we_c01;
  (* src = "structural/vending_structural.v:267.10-267.16" *)
  wire we_c02;
  (* src = "structural/vending_structural.v:268.10-268.16" *)
  wire we_c05;
  (* src = "structural/vending_structural.v:269.10-269.16" *)
  wire we_c10;
  (* src = "structural/vending_structural.v:276.10-276.21" *)
  wire we_coin_out;
  (* src = "structural/vending_structural.v:271.10-271.20" *)
  wire we_credito;
  (* src = "structural/vending_structural.v:270.10-270.26" *)
  wire we_current_price;
  (* src = "structural/vending_structural.v:272.10-272.24" *)
  wire we_disponibile;
  (* src = "structural/vending_structural.v:273.10-273.19" *)
  wire we_errore;
  (* src = "structural/vending_structural.v:262.10-262.21" *)
  wire we_price_p1;
  (* src = "structural/vending_structural.v:263.10-263.21" *)
  wire we_price_p2;
  (* src = "structural/vending_structural.v:264.10-264.21" *)
  wire we_price_p3;
  (* src = "structural/vending_structural.v:265.10-265.21" *)
  wire we_price_p4;
  (* src = "structural/vending_structural.v:275.10-275.17" *)
  wire we_prod;
  (* src = "structural/vending_structural.v:258.10-258.19" *)
  wire we_qty_p1;
  (* src = "structural/vending_structural.v:259.10-259.19" *)
  wire we_qty_p2;
  (* src = "structural/vending_structural.v:260.10-260.19" *)
  wire we_qty_p3;
  (* src = "structural/vending_structural.v:261.10-261.19" *)
  wire we_qty_p4;
  (* src = "structural/vending_structural.v:274.10-274.18" *)
  wire we_resto;
  assign _0219_ = ~qty_c10_q[0];
  assign _0220_ = ~qty_c05_q[0];
  assign _0221_ = ~qty_c02_q[0];
  assign _0222_ = ~clear_outputs;
  assign payout_active = do_ok | do_cancel;
  assign _0223_ = _0222_ & ~(payout_active);
  assign we_coin_out = ~_0223_;
  assign _0224_ = ~(coin10_q[4] & _0223_);
  assign _0225_ = ~(c10_calc[4] & payout_active);
  assign coin10_d[4] = ~(_0224_ & _0225_);
  assign _0226_ = ~(coin10_q[3] & _0223_);
  assign _0227_ = ~(c10_calc[3] & payout_active);
  assign coin10_d[3] = ~(_0226_ & _0227_);
  assign _0228_ = ~(coin10_q[2] & _0223_);
  assign _0229_ = ~(c10_calc[2] & payout_active);
  assign coin10_d[2] = ~(_0228_ & _0229_);
  assign _0230_ = ~(coin10_q[1] & _0223_);
  assign _0231_ = ~(c10_calc[1] & payout_active);
  assign coin10_d[1] = ~(_0230_ & _0231_);
  assign _0232_ = ~(coin10_q[0] & _0223_);
  assign _0233_ = ~(c10_calc[0] & payout_active);
  assign coin10_d[0] = ~(_0232_ & _0233_);
  assign _0234_ = ~(coin05_q[4] & _0223_);
  assign _0235_ = ~(c05_calc[4] & payout_active);
  assign coin05_d[4] = ~(_0234_ & _0235_);
  assign _0236_ = ~(coin05_q[3] & _0223_);
  assign _0237_ = ~(c05_calc[3] & payout_active);
  assign coin05_d[3] = ~(_0236_ & _0237_);
  assign _0238_ = ~(coin05_q[2] & _0223_);
  assign _0239_ = ~(c05_calc[2] & payout_active);
  assign coin05_d[2] = ~(_0238_ & _0239_);
  assign _0240_ = ~(coin05_q[1] & _0223_);
  assign _0241_ = ~(c05_calc[1] & payout_active);
  assign coin05_d[1] = ~(_0240_ & _0241_);
  assign _0242_ = ~(coin05_q[0] & _0223_);
  assign _0243_ = ~(c05_calc[0] & payout_active);
  assign coin05_d[0] = ~(_0242_ & _0243_);
  assign _0244_ = ~(coin02_q[4] & _0223_);
  assign _0245_ = ~(c02_calc[4] & payout_active);
  assign coin02_d[4] = ~(_0244_ & _0245_);
  assign _0246_ = ~(coin02_q[3] & _0223_);
  assign _0247_ = ~(c02_calc[3] & payout_active);
  assign coin02_d[3] = ~(_0246_ & _0247_);
  assign _0248_ = ~(coin02_q[2] & _0223_);
  assign _0249_ = ~(c02_calc[2] & payout_active);
  assign coin02_d[2] = ~(_0248_ & _0249_);
  assign _0250_ = ~(coin02_q[1] & _0223_);
  assign _0251_ = ~(c02_calc[1] & payout_active);
  assign coin02_d[1] = ~(_0250_ & _0251_);
  assign _0252_ = ~(coin02_q[0] & _0223_);
  assign _0253_ = ~(c02_calc[0] & payout_active);
  assign coin02_d[0] = ~(_0252_ & _0253_);
  assign _0254_ = ~(coin01_q[4] & _0223_);
  assign _0255_ = ~(c01_calc[4] & payout_active);
  assign coin01_d[4] = ~(_0254_ & _0255_);
  assign _0256_ = ~(coin01_q[3] & _0223_);
  assign _0257_ = ~(c01_calc[3] & payout_active);
  assign coin01_d[3] = ~(_0256_ & _0257_);
  assign _0258_ = ~(coin01_q[2] & _0223_);
  assign _0259_ = ~(c01_calc[2] & payout_active);
  assign coin01_d[2] = ~(_0258_ & _0259_);
  assign _0260_ = ~(coin01_q[1] & _0223_);
  assign _0261_ = ~(c01_calc[1] & payout_active);
  assign coin01_d[1] = ~(_0260_ & _0261_);
  assign _0262_ = ~(coin01_q[0] & _0223_);
  assign _0263_ = ~(c01_calc[0] & payout_active);
  assign coin01_d[0] = ~(_0262_ & _0263_);
  assign _0264_ = ~(clear_outputs | do_err);
  assign we_errore = ~_0264_;
  assign _0265_ = ~(resto_q[4] & _0264_);
  assign _0266_ = selezione[2] & do_err;
  assign _0267_ = _0266_ & ~(credito_ge_selprice);
  assign _0268_ = ~(sel_price[4] & _0267_);
  assign _0269_ = ~(_0265_ & _0268_);
  assign _0270_ = ~(c10_calc[0] & c05_calc[1]);
  assign _0271_ = c05_calc[0] & c05_calc[2];
  assign _0272_ = c05_calc[0] ^ c05_calc[2];
  assign _0273_ = ~(c10_calc[1] & _0272_);
  assign _0274_ = ~(c10_calc[1] ^ _0272_);
  assign _0275_ = _0270_ | _0274_;
  assign _0276_ = _0270_ ^ _0274_;
  assign _0277_ = ~(c02_calc[1] & _0276_);
  assign _0278_ = c10_calc[0] ^ c05_calc[1];
  assign _0279_ = ~(c02_calc[0] & _0278_);
  assign _0280_ = ~(c02_calc[1] ^ _0276_);
  assign _0281_ = _0279_ | _0280_;
  assign _0282_ = _0277_ & _0281_;
  assign _0283_ = ~(_0273_ & _0275_);
  assign _0284_ = c05_calc[1] & c05_calc[3];
  assign _0285_ = c05_calc[1] ^ c05_calc[3];
  assign _0286_ = _0271_ & _0285_;
  assign _0287_ = _0271_ ^ _0285_;
  assign _0288_ = c10_calc[0] & c10_calc[2];
  assign _0289_ = c10_calc[0] ^ c10_calc[2];
  assign _0290_ = ~(_0287_ & _0289_);
  assign _0291_ = _0287_ ^ _0289_;
  assign _0292_ = ~(_0283_ & _0291_);
  assign _0293_ = _0283_ ^ _0291_;
  assign _0294_ = ~(c02_calc[2] & _0293_);
  assign _0295_ = ~(c02_calc[2] ^ _0293_);
  assign _0296_ = _0282_ | _0295_;
  assign _0297_ = _0282_ ^ _0295_;
  assign _0298_ = ~(c01_calc[3] & _0297_);
  assign _0299_ = _0279_ ^ _0280_;
  assign _0300_ = ~(c01_calc[2] & _0299_);
  assign _0301_ = c02_calc[0] ^ _0278_;
  assign _0302_ = ~(c01_calc[1] & _0301_);
  assign _0303_ = ~(c05_calc[0] & c01_calc[0]);
  assign _0304_ = ~(c01_calc[1] ^ _0301_);
  assign _0305_ = _0303_ | _0304_;
  assign _0306_ = _0302_ & _0305_;
  assign _0307_ = ~(c01_calc[2] ^ _0299_);
  assign _0308_ = _0306_ | _0307_;
  assign _0309_ = _0300_ & _0308_;
  assign _0310_ = ~(c01_calc[3] ^ _0297_);
  assign _0311_ = _0309_ | _0310_;
  assign _0312_ = _0298_ & _0311_;
  assign _0313_ = _0294_ & _0296_;
  assign _0314_ = ~(_0290_ & _0292_);
  assign _0315_ = c05_calc[2] & c05_calc[4];
  assign _0316_ = c05_calc[2] ^ c05_calc[4];
  assign _0317_ = _0284_ & _0316_;
  assign _0318_ = _0284_ ^ _0316_;
  assign _0319_ = _0286_ & _0318_;
  assign _0320_ = _0286_ ^ _0318_;
  assign _0321_ = c10_calc[1] & c10_calc[3];
  assign _0322_ = c10_calc[1] ^ c10_calc[3];
  assign _0323_ = _0288_ & _0322_;
  assign _0324_ = _0288_ ^ _0322_;
  assign _0325_ = ~(_0320_ & _0324_);
  assign _0326_ = _0320_ ^ _0324_;
  assign _0327_ = ~(_0314_ & _0326_);
  assign _0328_ = _0314_ ^ _0326_;
  assign _0329_ = ~(c02_calc[3] & _0328_);
  assign _0330_ = ~(c02_calc[3] ^ _0328_);
  assign _0331_ = _0313_ | _0330_;
  assign _0332_ = _0313_ ^ _0330_;
  assign _0333_ = ~(c01_calc[4] & _0332_);
  assign _0334_ = ~(c01_calc[4] ^ _0332_);
  assign _0335_ = _0312_ | _0334_;
  assign _0336_ = _0312_ ^ _0334_;
  assign resto_d[4] = payout_active ? _0336_ : _0269_;
  assign _0337_ = ~(resto_q[3] & _0264_);
  assign _0338_ = ~(sel_price[3] & _0267_);
  assign _0339_ = ~(_0337_ & _0338_);
  assign _0340_ = _0309_ ^ _0310_;
  assign _0341_ = ~(_0309_ ^ _0310_);
  assign resto_d[3] = payout_active ? _0340_ : _0339_;
  assign _0342_ = ~(resto_q[2] & _0264_);
  assign _0343_ = ~(sel_price[2] & _0267_);
  assign _0344_ = ~(_0342_ & _0343_);
  assign _0345_ = _0306_ ^ _0307_;
  assign resto_d[2] = payout_active ? _0345_ : _0344_;
  assign _0346_ = ~(sel_price[1] & _0267_);
  assign _0347_ = ~(resto_q[1] & _0264_);
  assign _0348_ = ~(_0346_ & _0347_);
  assign _0349_ = _0303_ ^ _0304_;
  assign resto_d[1] = payout_active ? _0349_ : _0348_;
  assign _0350_ = ~(resto_q[0] & _0264_);
  assign _0351_ = ~(sel_price[0] & _0267_);
  assign _0352_ = ~(_0350_ & _0351_);
  assign _0353_ = c05_calc[0] ^ c01_calc[0];
  assign _0354_ = payout_active & _0353_;
  assign resto_d[0] = payout_active ? _0353_ : _0352_;
  assign _0355_ = errore_q[0] & _0264_;
  assign errore_d[0] = _0267_ | _0355_;
  assign _0356_ = init_counter_w[3] & ~(init_counter_w[2]);
  assign _0357_ = mode_init & _0356_;
  assign _0358_ = init_counter_w[0] & ~(init_counter_w[1]);
  assign _0359_ = ~(_0357_ & _0358_);
  assign _0360_ = ~(coin[1] & selezione[2]);
  assign _0361_ = coin[0] & selezione[1];
  assign _0362_ = coin[1] ^ selezione[2];
  assign _0363_ = ~(_0361_ & _0362_);
  assign _0364_ = _0360_ & _0363_;
  assign _0365_ = coin[1] & ~(_0364_);
  assign _0366_ = coin[2] | _0365_;
  assign _0367_ = coin[2] & coin[1];
  assign _0368_ = coin[0] & _0367_;
  assign _0369_ = coin[0] ? _0367_ : _0365_;
  assign _0370_ = _0366_ & ~(_0369_);
  assign _0371_ = ~(disponibile_q[7] & _0370_);
  assign _0372_ = coin[2] & ~(coin[1]);
  assign _0373_ = coin[0] & _0372_;
  assign _0374_ = ~(coin[2] & coin[0]);
  assign _0375_ = _0367_ & ~(coin[0]);
  assign _0376_ = _0372_ & ~(coin[0]);
  assign _0377_ = coin[2] & ~(coin[0]);
  assign _0378_ = coin[2] ^ coin[0];
  assign _0379_ = selezione[2] & selezione[0];
  assign _0380_ = coin[0] ^ selezione[1];
  assign _0381_ = _0379_ & _0380_;
  assign _0382_ = ~(_0362_ & _0381_);
  assign _0383_ = ~(_0364_ & _0382_);
  assign _0384_ = ~(_0378_ & _0383_);
  assign _0385_ = _0374_ & _0384_;
  assign _0386_ = ~(coin[1] ^ _0385_);
  assign _0387_ = ~(disponibile_q[6] & _0386_);
  assign _0388_ = _0378_ ^ _0383_;
  assign _0389_ = ~(disponibile_q[5] & _0388_);
  assign _0390_ = ~(_0361_ | _0381_);
  assign _0391_ = _0362_ ^ _0390_;
  assign _0392_ = ~(_0362_ ^ _0390_);
  assign _0393_ = ~(disponibile_q[4] & _0392_);
  assign _0394_ = _0379_ ^ _0380_;
  assign _0395_ = ~(disponibile_q[3] & _0394_);
  assign _0396_ = selezione[2] & ~(selezione[0]);
  assign _0397_ = selezione[2] ^ selezione[0];
  assign _0398_ = ~(disponibile_q[2] & _0397_);
  assign _0399_ = ~(disponibile_q[1] & selezione[1]);
  assign _0400_ = disponibile_q[0] & selezione[0];
  assign _0401_ = disponibile_q[1] ^ selezione[1];
  assign _0402_ = ~(_0400_ & _0401_);
  assign _0403_ = ~(_0399_ & _0402_);
  assign _0404_ = disponibile_q[2] ^ _0397_;
  assign _0405_ = ~(_0403_ & _0404_);
  assign _0406_ = ~(_0398_ & _0405_);
  assign _0407_ = disponibile_q[3] | _0394_;
  assign _0408_ = ~(_0406_ & _0407_);
  assign _0409_ = ~(_0395_ & _0408_);
  assign _0410_ = ~(disponibile_q[4] ^ _0391_);
  assign _0411_ = ~(_0409_ & _0410_);
  assign _0412_ = _0393_ & _0411_;
  assign _0413_ = ~(disponibile_q[5] | _0388_);
  assign _0414_ = _0412_ | _0413_;
  assign _0415_ = ~(_0389_ & _0414_);
  assign _0416_ = disponibile_q[6] ^ _0386_;
  assign _0417_ = ~(_0415_ & _0416_);
  assign _0418_ = _0387_ & _0417_;
  assign _0419_ = ~(disponibile_q[7] ^ _0370_);
  assign _0420_ = _0418_ | _0419_;
  assign _0421_ = _0371_ & _0420_;
  assign _0422_ = coin[0] | selezione[2];
  assign _0423_ = _0367_ & _0422_;
  assign _0424_ = ~(disponibile_q[8] & _0423_);
  assign _0425_ = ~(disponibile_q[8] ^ _0423_);
  assign _0426_ = init_counter_w[1] & ~(init_counter_w[0]);
  assign _0427_ = ~(_0357_ & _0426_);
  assign _0428_ = _0421_ | _0425_;
  assign _0429_ = _0421_ ^ _0425_;
  assign _0430_ = ~(disponibile_q[7] & _0386_);
  assign _0431_ = ~(disponibile_q[6] & _0388_);
  assign _0432_ = ~(disponibile_q[5] & _0392_);
  assign _0433_ = ~(disponibile_q[5] ^ _0391_);
  assign _0434_ = ~(disponibile_q[4] & _0394_);
  assign _0435_ = ~(disponibile_q[3] & _0397_);
  assign _0436_ = ~(disponibile_q[2] & selezione[1]);
  assign _0437_ = disponibile_q[1] & selezione[0];
  assign _0438_ = disponibile_q[2] ^ selezione[1];
  assign _0439_ = ~(_0437_ & _0438_);
  assign _0440_ = ~(_0436_ & _0439_);
  assign _0441_ = disponibile_q[3] | _0397_;
  assign _0442_ = ~(_0440_ & _0441_);
  assign _0443_ = _0435_ & _0442_;
  assign _0444_ = ~(disponibile_q[4] ^ _0394_);
  assign _0445_ = _0443_ | _0444_;
  assign _0446_ = ~(_0434_ & _0445_);
  assign _0447_ = ~(_0433_ & _0446_);
  assign _0448_ = _0432_ & _0447_;
  assign _0449_ = ~(disponibile_q[6] ^ _0388_);
  assign _0450_ = _0448_ | _0449_;
  assign _0451_ = ~(_0431_ & _0450_);
  assign _0452_ = disponibile_q[7] ^ _0386_;
  assign _0453_ = ~(_0451_ & _0452_);
  assign _0454_ = _0430_ & _0453_;
  assign _0455_ = ~(disponibile_q[8] & _0370_);
  assign _0456_ = ~(disponibile_q[8] ^ _0370_);
  assign _0457_ = mode_init & init_counter_w[1];
  assign _0458_ = init_counter_w[0] & _0457_;
  assign _0459_ = ~(_0356_ & _0458_);
  assign _0460_ = _0454_ | _0456_;
  assign _0461_ = _0454_ ^ _0456_;
  assign _0462_ = ~(disponibile_q[3] & _0368_);
  assign _0463_ = ~(disponibile_q[2] & _0375_);
  assign _0464_ = _0374_ | ~(disponibile_q[1]);
  assign _0465_ = disponibile_q[0] & _0377_;
  assign _0466_ = ~(disponibile_q[1] ^ _0374_);
  assign _0467_ = ~(_0465_ & _0466_);
  assign _0468_ = _0464_ & _0467_;
  assign _0469_ = ~(disponibile_q[2] ^ _0375_);
  assign _0470_ = _0468_ | _0469_;
  assign _0471_ = _0463_ & _0470_;
  assign _0472_ = ~(disponibile_q[3] | _0368_);
  assign _0473_ = _0471_ | _0472_;
  assign _0474_ = ~(_0462_ & _0473_);
  assign _0475_ = disponibile_q[4] & _0474_;
  assign _0476_ = disponibile_q[5] & _0475_;
  assign _0477_ = disponibile_q[6] & _0476_;
  assign _0478_ = disponibile_q[7] & _0477_;
  assign _0479_ = ~(disponibile_q[8] & _0478_);
  assign _0480_ = disponibile_q[8] ^ _0478_;
  assign _0481_ = disponibile_q[8] & ~(payout_active);
  assign _0482_ = c05_calc[3] & c05_calc[5];
  assign _0483_ = c05_calc[3] ^ c05_calc[5];
  assign _0484_ = _0315_ & _0483_;
  assign _0485_ = _0315_ ^ _0483_;
  assign _0486_ = _0317_ & _0485_;
  assign _0487_ = ~(c05_calc[4] & _0482_);
  assign _0488_ = c05_calc[4] ^ _0482_;
  assign _0489_ = _0488_ & ~(_0484_);
  assign _0490_ = ~(_0486_ & _0489_);
  assign _0491_ = c05_calc[5] & _0487_;
  assign _0492_ = ~(_0484_ & _0491_);
  assign _0493_ = ~(_0484_ ^ _0491_);
  assign _0494_ = ~(_0490_ & _0493_);
  assign _0495_ = c10_calc[2] & c10_calc[4];
  assign _0496_ = c10_calc[2] ^ c10_calc[4];
  assign _0497_ = _0321_ & _0496_;
  assign _0498_ = _0321_ ^ _0496_;
  assign _0499_ = _0323_ & _0498_;
  assign _0500_ = c10_calc[3] & c10_calc[5];
  assign _0501_ = c10_calc[3] ^ c10_calc[5];
  assign _0502_ = _0495_ & _0501_;
  assign _0503_ = _0495_ ^ _0501_;
  assign _0504_ = _0497_ & _0503_;
  assign _0505_ = _0497_ ^ _0503_;
  assign _0506_ = ~(_0499_ & _0505_);
  assign _0507_ = ~(c10_calc[4] & _0500_);
  assign _0508_ = c10_calc[4] ^ _0500_;
  assign _0509_ = _0508_ & ~(_0502_);
  assign _0510_ = ~(_0504_ & _0509_);
  assign _0511_ = ~(_0504_ ^ _0509_);
  assign _0512_ = ~(_0506_ & _0511_);
  assign _0513_ = ~(_0494_ & _0512_);
  assign _0514_ = _0494_ ^ _0512_;
  assign _0515_ = _0317_ ^ _0485_;
  assign _0516_ = ~(_0319_ & _0515_);
  assign _0517_ = ~(_0486_ ^ _0489_);
  assign _0518_ = ~(_0516_ & _0517_);
  assign _0519_ = _0499_ ^ _0505_;
  assign _0520_ = ~(_0518_ & _0519_);
  assign _0521_ = _0518_ ^ _0519_;
  assign _0522_ = _0319_ ^ _0515_;
  assign _0523_ = _0323_ ^ _0498_;
  assign _0524_ = ~(_0522_ & _0523_);
  assign _0525_ = ~(_0325_ & _0327_);
  assign _0526_ = _0522_ ^ _0523_;
  assign _0527_ = ~(_0525_ & _0526_);
  assign _0528_ = ~(_0524_ & _0527_);
  assign _0529_ = ~(_0521_ & _0528_);
  assign _0530_ = ~(_0520_ & _0529_);
  assign _0531_ = ~(_0514_ & _0530_);
  assign _0532_ = ~(_0513_ & _0531_);
  assign _0533_ = ~(_0487_ & _0492_);
  assign _0534_ = c10_calc[5] & _0507_;
  assign _0535_ = ~(_0502_ & _0534_);
  assign _0536_ = ~(_0502_ ^ _0534_);
  assign _0537_ = ~(_0510_ & _0536_);
  assign _0538_ = ~(_0533_ & _0537_);
  assign _0539_ = _0533_ ^ _0537_;
  assign _0540_ = ~(_0532_ & _0539_);
  assign _0541_ = _0507_ & _0535_;
  assign _0542_ = _0538_ & _0541_;
  assign _0543_ = _0540_ & _0542_;
  assign _0544_ = _0521_ ^ _0528_;
  assign _0545_ = ~(c02_calc[5] & _0544_);
  assign _0546_ = ~(c02_calc[5] ^ _0544_);
  assign _0547_ = _0525_ ^ _0526_;
  assign _0548_ = ~(c02_calc[4] & _0547_);
  assign _0549_ = _0329_ & _0331_;
  assign _0550_ = ~(c02_calc[4] ^ _0547_);
  assign _0551_ = _0549_ | _0550_;
  assign _0552_ = _0548_ & _0551_;
  assign _0553_ = _0546_ | _0552_;
  assign _0554_ = ~(_0545_ & _0553_);
  assign _0555_ = _0514_ ^ _0530_;
  assign _0556_ = ~(_0554_ & _0555_);
  assign _0557_ = _0532_ ^ _0539_;
  assign _0558_ = _0556_ | ~(_0557_);
  assign _0559_ = _0549_ ^ _0550_;
  assign _0560_ = ~(c01_calc[5] & _0559_);
  assign _0561_ = _0333_ & _0335_;
  assign _0562_ = ~(c01_calc[5] ^ _0559_);
  assign _0563_ = _0561_ | _0562_;
  assign _0564_ = ~(_0560_ & _0563_);
  assign _0565_ = ~(_0546_ ^ _0552_);
  assign _0566_ = _0564_ & ~(_0565_);
  assign _0567_ = _0554_ ^ _0555_;
  assign _0568_ = _0566_ & _0567_;
  assign _0569_ = ~(_0556_ ^ _0557_);
  assign _0570_ = ~(_0568_ & _0569_);
  assign _0571_ = _0558_ & _0570_;
  assign _0572_ = ~(_0543_ ^ _0571_);
  assign _0573_ = ~(disponibile_q[9] & _0572_);
  assign _0574_ = ~(_0568_ ^ _0569_);
  assign _0575_ = ~(disponibile_q[8] & _0574_);
  assign _0576_ = ~(_0566_ ^ _0567_);
  assign _0577_ = ~(disponibile_q[7] & _0576_);
  assign _0578_ = disponibile_q[7] ^ _0576_;
  assign _0579_ = _0564_ ^ _0565_;
  assign _0580_ = ~(disponibile_q[6] & _0579_);
  assign _0581_ = disponibile_q[6] ^ _0579_;
  assign _0582_ = _0561_ ^ _0562_;
  assign _0583_ = _0582_ | ~(disponibile_q[5]);
  assign _0584_ = ~(disponibile_q[5] ^ _0582_);
  assign _0585_ = _0336_ | ~(disponibile_q[4]);
  assign _0586_ = ~(disponibile_q[3] & _0341_);
  assign _0587_ = _0345_ | ~(disponibile_q[2]);
  assign _0588_ = _0349_ | ~(disponibile_q[1]);
  assign _0589_ = disponibile_q[0] | ~(_0353_);
  assign _0590_ = ~(disponibile_q[1] ^ _0349_);
  assign _0591_ = ~(_0589_ & _0590_);
  assign _0592_ = ~(_0588_ & _0591_);
  assign _0593_ = ~(disponibile_q[2] ^ _0345_);
  assign _0594_ = ~(_0592_ & _0593_);
  assign _0595_ = ~(_0587_ & _0594_);
  assign _0596_ = disponibile_q[3] | _0341_;
  assign _0597_ = ~(_0595_ & _0596_);
  assign _0598_ = ~(_0586_ & _0597_);
  assign _0599_ = ~(disponibile_q[4] ^ _0336_);
  assign _0600_ = ~(_0598_ & _0599_);
  assign _0601_ = ~(_0585_ & _0600_);
  assign _0602_ = ~(_0584_ & _0601_);
  assign _0603_ = ~(_0583_ & _0602_);
  assign _0604_ = ~(_0581_ & _0603_);
  assign _0605_ = ~(_0580_ & _0604_);
  assign _0606_ = ~(_0578_ & _0605_);
  assign _0607_ = ~(_0577_ & _0606_);
  assign _0608_ = disponibile_q[8] ^ _0574_;
  assign _0609_ = ~(_0607_ & _0608_);
  assign _0610_ = ~(_0575_ & _0609_);
  assign _0611_ = disponibile_q[9] | _0572_;
  assign _0612_ = ~(_0610_ & _0611_);
  assign _0613_ = ~(_0573_ & _0612_);
  assign _0614_ = _0607_ ^ _0608_;
  assign _0615_ = payout_active & _0614_;
  assign _0616_ = _0613_ & _0615_;
  assign _0617_ = _0481_ | _0616_;
  assign _0618_ = do_add_coin ? _0480_ : _0617_;
  assign _0619_ = _0459_ ? _0618_ : _0461_;
  assign _0620_ = _0427_ ? _0619_ : _0429_;
  assign _0621_ = ~(disponibile_q[6] & coin[2]);
  assign _0622_ = ~(disponibile_q[5] & coin[1]);
  assign _0623_ = ~(disponibile_q[4] & coin[0]);
  assign _0624_ = ~(disponibile_q[3] & selezione[2]);
  assign _0625_ = disponibile_q[3] | selezione[2];
  assign _0626_ = ~(_0440_ & _0625_);
  assign _0627_ = ~(_0624_ & _0626_);
  assign _0628_ = disponibile_q[4] ^ coin[0];
  assign _0629_ = ~(_0627_ & _0628_);
  assign _0630_ = ~(_0623_ & _0629_);
  assign _0631_ = disponibile_q[5] ^ coin[1];
  assign _0632_ = ~(_0630_ & _0631_);
  assign _0633_ = ~(_0622_ & _0632_);
  assign _0634_ = disponibile_q[6] ^ coin[2];
  assign _0635_ = ~(_0633_ & _0634_);
  assign _0636_ = ~(_0621_ & _0635_);
  assign _0637_ = disponibile_q[7] & _0636_;
  assign _0638_ = ~(disponibile_q[8] & _0637_);
  assign _0639_ = disponibile_q[8] ^ _0637_;
  assign _0640_ = _0359_ ? _0620_ : _0639_;
  assign _0641_ = ~(init_counter_w[1] | init_counter_w[0]);
  assign _0642_ = ~(_0357_ & _0641_);
  assign disponibile_d[8] = _0640_ & _0642_;
  assign _0643_ = _0418_ ^ _0419_;
  assign _0644_ = _0451_ ^ _0452_;
  assign _0645_ = disponibile_q[7] ^ _0477_;
  assign _0646_ = disponibile_q[7] & ~(payout_active);
  assign _0647_ = _0578_ | _0605_;
  assign _0648_ = payout_active & _0606_;
  assign _0649_ = _0647_ & _0648_;
  assign _0650_ = _0613_ & _0649_;
  assign _0651_ = _0646_ | _0650_;
  assign _0652_ = do_add_coin ? _0645_ : _0651_;
  assign _0653_ = _0459_ ? _0652_ : _0644_;
  assign _0654_ = _0427_ ? _0653_ : _0643_;
  assign _0655_ = disponibile_q[7] ^ _0636_;
  assign _0656_ = _0359_ ? _0654_ : _0655_;
  assign disponibile_d[7] = _0642_ & _0656_;
  assign _0657_ = disponibile_q[6] ^ _0476_;
  assign _0658_ = disponibile_q[6] & ~(payout_active);
  assign _0659_ = _0581_ ^ _0603_;
  assign _0660_ = payout_active & _0659_;
  assign _0661_ = _0613_ & _0660_;
  assign _0662_ = _0658_ | _0661_;
  assign _0663_ = do_add_coin ? _0657_ : _0662_;
  assign _0664_ = _0448_ ^ _0449_;
  assign _0665_ = _0459_ ? _0663_ : _0664_;
  assign _0666_ = _0415_ ^ _0416_;
  assign _0667_ = _0427_ ? _0665_ : _0666_;
  assign _0668_ = _0633_ ^ _0634_;
  assign _0669_ = _0359_ ? _0667_ : _0668_;
  assign disponibile_d[6] = _0642_ & _0669_;
  assign _0670_ = disponibile_q[5] & ~(payout_active);
  assign _0671_ = _0584_ ^ _0601_;
  assign _0672_ = payout_active & _0671_;
  assign _0673_ = _0613_ & _0672_;
  assign _0674_ = _0670_ | _0673_;
  assign _0675_ = disponibile_q[5] ^ _0475_;
  assign _0676_ = do_add_coin ? _0675_ : _0674_;
  assign _0677_ = _0433_ ^ _0446_;
  assign _0678_ = _0459_ ? _0676_ : _0677_;
  assign _0679_ = ~(_0427_ & _0678_);
  assign _0680_ = ~(disponibile_q[5] ^ _0388_);
  assign _0681_ = ~(_0412_ & _0680_);
  assign _0682_ = _0412_ | _0680_;
  assign _0683_ = _0682_ & ~(_0427_);
  assign _0684_ = ~(_0681_ & _0683_);
  assign _0685_ = ~(_0679_ & _0684_);
  assign _0686_ = _0630_ ^ _0631_;
  assign _0687_ = _0359_ ? _0685_ : _0686_;
  assign disponibile_d[5] = _0642_ ? _0687_ : coin[2];
  assign _0688_ = disponibile_q[4] & ~(payout_active);
  assign _0689_ = _0598_ ^ _0599_;
  assign _0690_ = payout_active & _0689_;
  assign _0691_ = _0613_ & _0690_;
  assign _0692_ = _0688_ | _0691_;
  assign _0693_ = disponibile_q[4] ^ _0474_;
  assign _0694_ = do_add_coin ? _0693_ : _0692_;
  assign _0695_ = _0443_ ^ _0444_;
  assign _0696_ = _0459_ ? _0694_ : _0695_;
  assign _0697_ = _0409_ ^ _0410_;
  assign _0698_ = _0427_ ? _0696_ : _0697_;
  assign _0699_ = _0627_ ^ _0628_;
  assign _0700_ = _0359_ ? _0698_ : _0699_;
  assign disponibile_d[4] = _0642_ ? _0700_ : coin[1];
  assign _0701_ = disponibile_q[3] & ~(payout_active);
  assign _0702_ = _0586_ & _0596_;
  assign _0703_ = ~(_0595_ ^ _0702_);
  assign _0704_ = payout_active & ~(_0703_);
  assign _0705_ = _0613_ & _0704_;
  assign _0706_ = ~(_0701_ | _0705_);
  assign _0707_ = do_add_coin | _0706_;
  assign _0708_ = ~(disponibile_q[3] ^ _0368_);
  assign _0709_ = ~(_0471_ & _0708_);
  assign _0710_ = _0471_ | _0708_;
  assign _0711_ = do_add_coin & _0710_;
  assign _0712_ = ~(_0709_ & _0711_);
  assign _0713_ = ~(_0707_ & _0712_);
  assign _0714_ = ~(_0435_ & _0441_);
  assign _0715_ = ~(_0440_ ^ _0714_);
  assign _0716_ = _0459_ ? _0713_ : _0715_;
  assign _0717_ = ~(_0395_ & _0407_);
  assign _0718_ = ~(_0406_ ^ _0717_);
  assign _0719_ = _0427_ ? _0716_ : _0718_;
  assign _0720_ = ~(_0359_ & _0719_);
  assign _0721_ = _0624_ & _0625_;
  assign _0722_ = _0440_ | _0721_;
  assign _0723_ = ~(_0440_ & _0721_);
  assign _0724_ = _0723_ & ~(_0359_);
  assign _0725_ = ~(_0722_ & _0724_);
  assign _0726_ = ~(_0720_ & _0725_);
  assign disponibile_d[3] = _0642_ ? _0726_ : coin[0];
  assign _0727_ = disponibile_q[2] & ~(payout_active);
  assign _0728_ = _0592_ ^ _0593_;
  assign _0729_ = payout_active & _0728_;
  assign _0730_ = _0613_ & _0729_;
  assign _0731_ = _0727_ | _0730_;
  assign _0732_ = _0468_ ^ _0469_;
  assign _0733_ = do_add_coin ? _0732_ : _0731_;
  assign _0734_ = _0437_ ^ _0438_;
  assign _0735_ = _0459_ ? _0733_ : _0734_;
  assign _0736_ = _0403_ ^ _0404_;
  assign _0737_ = _0427_ ? _0735_ : _0736_;
  assign _0738_ = _0359_ ? _0737_ : _0734_;
  assign _0739_ = selezione[2] & ~(_0642_);
  assign disponibile_d[2] = _0642_ ? _0738_ : selezione[2];
  assign _0740_ = disponibile_q[1] & ~(payout_active);
  assign _0741_ = _0589_ ^ _0590_;
  assign _0742_ = payout_active & _0741_;
  assign _0743_ = _0613_ & _0742_;
  assign _0744_ = _0740_ | _0743_;
  assign _0745_ = _0465_ ^ _0466_;
  assign _0746_ = do_add_coin ? _0745_ : _0744_;
  assign _0747_ = disponibile_q[1] ^ selezione[0];
  assign _0748_ = _0459_ ? _0746_ : _0747_;
  assign _0749_ = _0400_ ^ _0401_;
  assign _0750_ = _0427_ ? _0748_ : _0749_;
  assign _0751_ = _0359_ ? _0750_ : _0747_;
  assign _0752_ = selezione[1] & ~(_0642_);
  assign disponibile_d[1] = _0642_ ? _0751_ : selezione[1];
  assign _0753_ = _0613_ | ~(payout_active);
  assign _0754_ = ~(disponibile_q[0] ^ _0354_);
  assign _0755_ = ~(do_add_coin | _0754_);
  assign _0756_ = ~(_0753_ & _0755_);
  assign _0757_ = disponibile_q[0] ^ _0377_;
  assign _0758_ = ~(do_add_coin & _0757_);
  assign _0759_ = ~(_0756_ & _0758_);
  assign _0760_ = _0459_ ? _0759_ : disponibile_q[0];
  assign _0761_ = disponibile_q[0] ^ selezione[0];
  assign _0762_ = _0427_ ? _0760_ : _0761_;
  assign _0763_ = _0359_ ? _0762_ : disponibile_q[0];
  assign _0764_ = selezione[0] & ~(_0642_);
  assign disponibile_d[0] = _0642_ ? _0763_ : selezione[0];
  assign _0765_ = ~(credito_q[3] & _0368_);
  assign _0766_ = ~(credito_q[2] & _0375_);
  assign _0767_ = _0374_ | ~(credito_q[1]);
  assign _0768_ = credito_q[0] & _0377_;
  assign _0769_ = ~(credito_q[1] ^ _0374_);
  assign _0770_ = ~(_0768_ & _0769_);
  assign _0771_ = _0767_ & _0770_;
  assign _0772_ = ~(credito_q[2] ^ _0375_);
  assign _0773_ = _0771_ | _0772_;
  assign _0774_ = ~(_0766_ & _0773_);
  assign _0775_ = credito_q[3] | _0368_;
  assign _0776_ = ~(_0774_ & _0775_);
  assign _0777_ = ~(_0765_ & _0776_);
  assign _0778_ = do_add_coin & _0777_;
  assign _0779_ = credito_q[4] | _0778_;
  assign _0780_ = ~(credito_q[4] & _0778_);
  assign _0781_ = ~(mode_init | payout_active);
  assign _0782_ = _0779_ & _0781_;
  assign credito_d[4] = _0780_ & _0782_;
  assign _0783_ = ~(_0765_ & _0775_);
  assign _0784_ = ~(_0774_ ^ _0783_);
  assign _0785_ = do_add_coin ? _0784_ : credito_q[3];
  assign credito_d[3] = _0781_ & _0785_;
  assign _0786_ = _0771_ ^ _0772_;
  assign _0787_ = do_add_coin ? _0786_ : credito_q[2];
  assign credito_d[2] = _0781_ & _0787_;
  assign _0788_ = ~(_0768_ ^ _0769_);
  assign _0789_ = ~(do_add_coin & _0788_);
  assign _0790_ = credito_q[1] | do_add_coin;
  assign _0791_ = _0781_ & _0790_;
  assign credito_d[1] = _0789_ & _0791_;
  assign _0792_ = do_add_coin & _0377_;
  assign _0793_ = ~(credito_q[0] & _0792_);
  assign _0794_ = credito_q[0] | _0792_;
  assign _0795_ = _0781_ & _0794_;
  assign credito_d[0] = _0793_ & _0795_;
  assign _0796_ = qty_c10_q[1] & qty_c10_q[0];
  assign _0797_ = qty_c10_q[2] & _0796_;
  assign _0798_ = qty_c10_q[3] & _0797_;
  assign _0799_ = ~(qty_c10_q[4] & _0798_);
  assign _0800_ = ~(do_add_coin & _0368_);
  assign _0801_ = payout_active ? qc10_next[4] : qty_c10_q[4];
  assign _0802_ = qty_c10_q[4] ^ _0798_;
  assign _0803_ = _0800_ ? _0801_ : _0802_;
  assign qty_c10_d[4] = _0459_ ? _0803_ : coin[1];
  assign _0804_ = payout_active ? qc10_next[3] : qty_c10_q[3];
  assign _0805_ = qty_c10_q[3] ^ _0797_;
  assign _0806_ = _0800_ ? _0804_ : _0805_;
  assign qty_c10_d[3] = _0459_ ? _0806_ : coin[0];
  assign _0807_ = qty_c10_q[2] ^ _0796_;
  assign _0808_ = payout_active ? qc10_next[2] : qty_c10_q[2];
  assign _0809_ = _0800_ ? _0808_ : _0807_;
  assign qty_c10_d[2] = _0459_ ? _0809_ : selezione[2];
  assign _0810_ = qty_c10_q[1] ^ qty_c10_q[0];
  assign _0811_ = payout_active ? qc10_next[1] : qty_c10_q[1];
  assign _0812_ = _0800_ ? _0811_ : _0810_;
  assign qty_c10_d[1] = _0459_ ? _0812_ : selezione[1];
  assign _0813_ = payout_active ? qc10_next[0] : qty_c10_q[0];
  assign _0814_ = _0800_ ? _0813_ : _0219_;
  assign qty_c10_d[0] = _0459_ ? _0814_ : selezione[0];
  assign _0001_ = qty_c05_q[1] & qty_c05_q[0];
  assign _0002_ = qty_c05_q[2] & _0001_;
  assign _0003_ = qty_c05_q[3] & _0002_;
  assign _0004_ = ~(qty_c05_q[4] & _0003_);
  assign _0005_ = ~(do_add_coin & _0375_);
  assign _0006_ = payout_active ? qc05_next[4] : qty_c05_q[4];
  assign _0007_ = qty_c05_q[4] ^ _0003_;
  assign _0008_ = _0005_ ? _0006_ : _0007_;
  assign qty_c05_d[4] = _0427_ ? _0008_ : coin[1];
  assign _0009_ = payout_active ? qc05_next[3] : qty_c05_q[3];
  assign _0010_ = qty_c05_q[3] ^ _0002_;
  assign _0011_ = _0005_ ? _0009_ : _0010_;
  assign qty_c05_d[3] = _0427_ ? _0011_ : coin[0];
  assign _0012_ = qty_c05_q[2] ^ _0001_;
  assign _0013_ = payout_active ? qc05_next[2] : qty_c05_q[2];
  assign _0014_ = _0005_ ? _0013_ : _0012_;
  assign qty_c05_d[2] = _0427_ ? _0014_ : selezione[2];
  assign _0015_ = qty_c05_q[1] ^ qty_c05_q[0];
  assign _0016_ = payout_active ? qc05_next[1] : qty_c05_q[1];
  assign _0017_ = _0005_ ? _0016_ : _0015_;
  assign qty_c05_d[1] = _0427_ ? _0017_ : selezione[1];
  assign _0018_ = payout_active ? qc05_next[0] : qty_c05_q[0];
  assign _0019_ = _0005_ ? _0018_ : _0220_;
  assign qty_c05_d[0] = _0427_ ? _0019_ : selezione[0];
  assign _0020_ = qty_c02_q[1] & qty_c02_q[0];
  assign _0021_ = qty_c02_q[2] & _0020_;
  assign _0022_ = qty_c02_q[3] & _0021_;
  assign _0023_ = ~(qty_c02_q[4] & _0022_);
  assign _0024_ = ~(do_add_coin & _0373_);
  assign _0025_ = payout_active ? qc02_next[4] : qty_c02_q[4];
  assign _0026_ = qty_c02_q[4] ^ _0022_;
  assign _0027_ = _0024_ ? _0025_ : _0026_;
  assign qty_c02_d[4] = _0359_ ? _0027_ : coin[1];
  assign _0028_ = payout_active ? qc02_next[3] : qty_c02_q[3];
  assign _0029_ = qty_c02_q[3] ^ _0021_;
  assign _0030_ = _0024_ ? _0028_ : _0029_;
  assign qty_c02_d[3] = _0359_ ? _0030_ : coin[0];
  assign _0031_ = qty_c02_q[2] ^ _0020_;
  assign _0032_ = payout_active ? qc02_next[2] : qty_c02_q[2];
  assign _0033_ = _0024_ ? _0032_ : _0031_;
  assign qty_c02_d[2] = _0359_ ? _0033_ : selezione[2];
  assign _0034_ = qty_c02_q[1] ^ qty_c02_q[0];
  assign _0035_ = payout_active ? qc02_next[1] : qty_c02_q[1];
  assign _0036_ = _0024_ ? _0035_ : _0034_;
  assign qty_c02_d[1] = _0359_ ? _0036_ : selezione[1];
  assign _0037_ = payout_active ? qc02_next[0] : qty_c02_q[0];
  assign _0038_ = _0024_ ? _0037_ : _0221_;
  assign qty_c02_d[0] = _0359_ ? _0038_ : selezione[0];
  assign _0039_ = do_add_coin & _0376_;
  assign _0040_ = qty_c01_q[1] & qty_c01_q[0];
  assign _0041_ = qty_c01_q[2] & _0040_;
  assign _0042_ = qty_c01_q[3] & _0041_;
  assign _0043_ = ~(payout_active | _0039_);
  assign _0044_ = ~(qty_c01_q[4] & _0042_);
  assign _0045_ = qty_c01_q[4] ^ _0042_;
  assign _0046_ = payout_active ? qc01_next[4] : qty_c01_q[4];
  assign _0047_ = _0039_ ? _0045_ : _0046_;
  assign qty_c01_d[4] = _0642_ ? _0047_ : coin[1];
  assign _0048_ = qty_c01_q[3] ^ _0041_;
  assign _0049_ = payout_active ? qc01_next[3] : qty_c01_q[3];
  assign _0050_ = _0039_ ? _0048_ : _0049_;
  assign qty_c01_d[3] = _0642_ ? _0050_ : coin[0];
  assign _0051_ = payout_active ? qc01_next[2] : qty_c01_q[2];
  assign _0052_ = _0039_ | _0051_;
  assign _0053_ = ~(qty_c01_q[2] ^ _0040_);
  assign _0054_ = ~(_0039_ & _0053_);
  assign _0055_ = _0642_ & _0052_;
  assign _0056_ = _0054_ & _0055_;
  assign qty_c01_d[2] = _0739_ | _0056_;
  assign _0057_ = payout_active ? qc01_next[1] : qty_c01_q[1];
  assign _0058_ = _0039_ | _0057_;
  assign _0059_ = ~(qty_c01_q[1] ^ qty_c01_q[0]);
  assign _0060_ = ~(_0039_ & _0059_);
  assign _0061_ = _0642_ & _0058_;
  assign _0062_ = _0060_ & _0061_;
  assign qty_c01_d[1] = _0752_ | _0062_;
  assign _0063_ = ~(qty_c01_q[0] & _0039_);
  assign _0064_ = payout_active ? qc01_next[0] : qty_c01_q[0];
  assign _0065_ = _0039_ | _0064_;
  assign _0066_ = _0642_ & _0065_;
  assign _0067_ = _0063_ & _0066_;
  assign qty_c01_d[0] = _0764_ | _0067_;
  assign _0068_ = init_counter_w[2] & ~(init_counter_w[3]);
  assign _0069_ = ~(_0458_ & _0068_);
  assign init_price_p4 = ~_0069_;
  assign price_p4_d[4] = _0069_ ? price_p4_q[4] : coin[1];
  assign price_p4_d[3] = _0069_ ? price_p4_q[3] : coin[0];
  assign price_p4_d[2] = _0069_ ? price_p4_q[2] : selezione[2];
  assign price_p4_d[1] = _0069_ ? price_p4_q[1] : selezione[1];
  assign price_p4_d[0] = _0069_ ? price_p4_q[0] : selezione[0];
  assign _0070_ = mode_init & _0358_;
  assign _0071_ = ~(_0068_ & _0070_);
  assign init_price_p3 = ~_0071_;
  assign price_p3_d[4] = _0071_ ? price_p3_q[4] : coin[1];
  assign price_p3_d[3] = _0071_ ? price_p3_q[3] : coin[0];
  assign price_p3_d[2] = _0071_ ? price_p3_q[2] : selezione[2];
  assign price_p3_d[1] = _0071_ ? price_p3_q[1] : selezione[1];
  assign price_p3_d[0] = _0071_ ? price_p3_q[0] : selezione[0];
  assign _0072_ = ~(init_counter_w[2] | init_counter_w[3]);
  assign _0073_ = ~(_0458_ & _0072_);
  assign init_price_p2 = ~_0073_;
  assign price_p2_d[4] = _0073_ ? price_p2_q[4] : coin[1];
  assign price_p2_d[3] = _0073_ ? price_p2_q[3] : coin[0];
  assign price_p2_d[2] = _0073_ ? price_p2_q[2] : selezione[2];
  assign price_p2_d[1] = _0073_ ? price_p2_q[1] : selezione[1];
  assign price_p2_d[0] = _0073_ ? price_p2_q[0] : selezione[0];
  assign _0074_ = ~(_0070_ & _0072_);
  assign init_price_p1 = ~_0074_;
  assign price_p1_d[4] = _0074_ ? price_p1_q[4] : coin[1];
  assign price_p1_d[3] = _0074_ ? price_p1_q[3] : coin[0];
  assign price_p1_d[2] = _0074_ ? price_p1_q[2] : selezione[2];
  assign price_p1_d[1] = _0074_ ? price_p1_q[1] : selezione[1];
  assign price_p1_d[0] = _0074_ ? price_p1_q[0] : selezione[0];
  assign _0075_ = mode_init & _0426_;
  assign _0076_ = ~(_0068_ & _0075_);
  assign _0077_ = selezione[1] & do_ok;
  assign _0078_ = ~(_0379_ & _0077_);
  assign _0079_ = qty_p4_q[0] | _0078_;
  assign _0080_ = qty_p4_q[1] | _0079_;
  assign _0081_ = qty_p4_q[2] | _0080_;
  assign _0082_ = qty_p4_q[3] | _0081_;
  assign _0083_ = qty_p4_q[4] | _0082_;
  assign _0084_ = ~(qty_p4_q[4] ^ _0082_);
  assign qty_p4_d[4] = _0076_ ? _0084_ : coin[1];
  assign _0085_ = ~(qty_p4_q[3] ^ _0081_);
  assign qty_p4_d[3] = _0076_ ? _0085_ : coin[0];
  assign _0086_ = ~(qty_p4_q[2] ^ _0080_);
  assign qty_p4_d[2] = _0076_ ? _0086_ : selezione[2];
  assign _0087_ = ~(qty_p4_q[1] ^ _0079_);
  assign qty_p4_d[1] = _0076_ ? _0087_ : selezione[1];
  assign _0088_ = ~(qty_p4_q[0] ^ _0078_);
  assign qty_p4_d[0] = _0076_ ? _0088_ : selezione[0];
  assign _0089_ = mode_init & _0641_;
  assign _0090_ = ~(_0068_ & _0089_);
  assign _0091_ = ~(_0396_ & _0077_);
  assign _0092_ = qty_p3_q[0] | _0091_;
  assign _0093_ = qty_p3_q[1] | _0092_;
  assign _0094_ = qty_p3_q[2] | _0093_;
  assign _0095_ = qty_p3_q[3] | _0094_;
  assign _0096_ = qty_p3_q[4] | _0095_;
  assign _0097_ = ~(qty_p3_q[4] ^ _0095_);
  assign qty_p3_d[4] = _0090_ ? _0097_ : coin[1];
  assign _0098_ = ~(qty_p3_q[3] ^ _0094_);
  assign qty_p3_d[3] = _0090_ ? _0098_ : coin[0];
  assign _0099_ = ~(qty_p3_q[2] ^ _0093_);
  assign qty_p3_d[2] = _0090_ ? _0099_ : selezione[2];
  assign _0100_ = ~(qty_p3_q[1] ^ _0092_);
  assign qty_p3_d[1] = _0090_ ? _0100_ : selezione[1];
  assign _0101_ = ~(qty_p3_q[0] ^ _0091_);
  assign qty_p3_d[0] = _0090_ ? _0101_ : selezione[0];
  assign _0102_ = ~(_0072_ & _0075_);
  assign _0103_ = do_ok & ~(selezione[1]);
  assign _0104_ = ~(_0379_ & _0103_);
  assign _0105_ = qty_p2_q[0] | _0104_;
  assign _0106_ = qty_p2_q[1] | _0105_;
  assign _0107_ = qty_p2_q[2] | _0106_;
  assign _0108_ = qty_p2_q[3] | _0107_;
  assign _0109_ = qty_p2_q[4] | _0108_;
  assign _0110_ = ~(qty_p2_q[4] ^ _0108_);
  assign qty_p2_d[4] = _0102_ ? _0110_ : coin[1];
  assign _0111_ = ~(qty_p2_q[3] ^ _0107_);
  assign qty_p2_d[3] = _0102_ ? _0111_ : coin[0];
  assign _0112_ = ~(qty_p2_q[2] ^ _0106_);
  assign qty_p2_d[2] = _0102_ ? _0112_ : selezione[2];
  assign _0113_ = ~(qty_p2_q[1] ^ _0105_);
  assign qty_p2_d[1] = _0102_ ? _0113_ : selezione[1];
  assign _0114_ = ~(qty_p2_q[0] ^ _0104_);
  assign qty_p2_d[0] = _0102_ ? _0114_ : selezione[0];
  assign _0115_ = ~(_0072_ & _0089_);
  assign _0116_ = ~(_0396_ & _0103_);
  assign _0117_ = qty_p1_q[0] | _0116_;
  assign _0118_ = qty_p1_q[1] | _0117_;
  assign _0119_ = qty_p1_q[2] | _0118_;
  assign _0120_ = qty_p1_q[3] | _0119_;
  assign _0121_ = qty_p1_q[4] | _0120_;
  assign _0122_ = ~(qty_p1_q[4] ^ _0120_);
  assign qty_p1_d[4] = _0115_ ? _0122_ : coin[1];
  assign _0123_ = ~(qty_p1_q[3] ^ _0119_);
  assign qty_p1_d[3] = _0115_ ? _0123_ : coin[0];
  assign _0124_ = ~(qty_p1_q[2] ^ _0118_);
  assign qty_p1_d[2] = _0115_ ? _0124_ : selezione[2];
  assign _0125_ = ~(qty_p1_q[1] ^ _0117_);
  assign qty_p1_d[1] = _0115_ ? _0125_ : selezione[1];
  assign _0126_ = ~(qty_p1_q[0] ^ _0116_);
  assign qty_p1_d[0] = _0115_ ? _0126_ : selezione[0];
  assign _0127_ = do_ok | ~(credito_q[4]);
  assign _0128_ = sel_price[3] | ~(credito_q[3]);
  assign _0129_ = sel_price[2] | ~(credito_q[2]);
  assign _0130_ = sel_price[1] | ~(credito_q[1]);
  assign _0131_ = credito_q[0] | ~(sel_price[0]);
  assign _0132_ = ~(credito_q[1] ^ sel_price[1]);
  assign _0133_ = ~(_0131_ & _0132_);
  assign _0134_ = ~(_0130_ & _0133_);
  assign _0135_ = ~(credito_q[2] ^ sel_price[2]);
  assign _0136_ = ~(_0134_ & _0135_);
  assign _0137_ = ~(_0129_ & _0136_);
  assign _0138_ = credito_q[3] | ~(sel_price[3]);
  assign _0139_ = ~(_0137_ & _0138_);
  assign _0140_ = _0128_ & _0139_;
  assign _0141_ = sel_price[4] | ~(credito_q[4]);
  assign _0142_ = credito_q[4] ^ sel_price[4];
  assign _0143_ = ~(_0140_ & _0142_);
  assign _0144_ = _0140_ | _0142_;
  assign _0145_ = do_ok & _0143_;
  assign _0146_ = ~(_0144_ & _0145_);
  assign payout_amount[4] = ~(_0127_ & _0146_);
  assign _0147_ = do_ok | ~(credito_q[3]);
  assign _0148_ = _0128_ & _0138_;
  assign _0149_ = _0137_ | _0148_;
  assign _0150_ = ~(_0137_ & _0148_);
  assign _0151_ = do_ok & _0150_;
  assign _0152_ = ~(_0149_ & _0151_);
  assign payout_amount[3] = ~(_0147_ & _0152_);
  assign _0153_ = _0134_ ^ _0135_;
  assign payout_amount[2] = do_ok ? _0153_ : credito_q[2];
  assign _0154_ = _0131_ ^ _0132_;
  assign payout_amount[1] = do_ok ? _0154_ : credito_q[1];
  assign _0155_ = credito_q[0] ^ sel_price[0];
  assign payout_amount[0] = do_ok ? _0155_ : credito_q[0];
  assign _0156_ = ~(sel_qty[3] | sel_qty[0]);
  assign _0157_ = _0156_ & ~(sel_qty[1]);
  assign _0158_ = selezione[2] & ~(sel_qty[4]);
  assign _0159_ = ~(sel_qty[5] | sel_qty[2]);
  assign _0160_ = _0158_ & _0159_;
  assign _0000_ = ~(_0157_ & _0160_);
  assign we_qty_p1 = ~(_0115_ & _0116_);
  assign we_qty_p2 = ~(_0102_ & _0104_);
  assign we_qty_p3 = ~(_0090_ & _0091_);
  assign we_qty_p4 = ~(_0076_ & _0078_);
  assign we_c01 = ~(_0642_ & _0043_);
  assign _0161_ = _0024_ & ~(payout_active);
  assign we_c02 = ~(_0359_ & _0161_);
  assign _0162_ = _0005_ & ~(payout_active);
  assign we_c05 = ~(_0427_ & _0162_);
  assign _0163_ = _0800_ & ~(payout_active);
  assign we_c10 = ~(_0459_ & _0163_);
  assign we_credito = do_add_coin | ~(_0781_);
  assign _0164_ = do_add_coin | payout_active;
  assign we_disponibile = _0357_ | _0164_;
  assign we_resto = payout_active | ~(_0264_);
  assign we_prod = clear_outputs | do_ok;
  assign _0165_ = _0141_ & _0144_;
  assign _0166_ = ~(sel_price[5] & _0165_);
  assign _0167_ = sel_price[5] | _0165_;
  assign _0168_ = do_ok & _0167_;
  assign _0169_ = ~(_0166_ & _0168_);
  assign payout_amount[5] = ~(credito_q[5] ^ _0169_);
  assign _0170_ = ~(qty_p1_q[5] ^ _0121_);
  assign qty_p1_d[5] = _0115_ ? _0170_ : coin[2];
  assign _0171_ = ~(qty_p2_q[5] ^ _0109_);
  assign qty_p2_d[5] = _0102_ ? _0171_ : coin[2];
  assign _0172_ = ~(qty_p3_q[5] ^ _0096_);
  assign qty_p3_d[5] = _0090_ ? _0172_ : coin[2];
  assign _0173_ = ~(qty_p4_q[5] ^ _0083_);
  assign qty_p4_d[5] = _0076_ ? _0173_ : coin[2];
  assign price_p1_d[5] = _0074_ ? price_p1_q[5] : coin[2];
  assign price_p2_d[5] = _0073_ ? price_p2_q[5] : coin[2];
  assign price_p3_d[5] = _0071_ ? price_p3_q[5] : coin[2];
  assign price_p4_d[5] = _0069_ ? price_p4_q[5] : coin[2];
  assign _0174_ = ~(qty_c01_q[5] ^ _0044_);
  assign _0175_ = payout_active ? qc01_next[5] : qty_c01_q[5];
  assign _0176_ = _0039_ ? _0174_ : _0175_;
  assign qty_c01_d[5] = _0642_ ? _0176_ : coin[2];
  assign _0177_ = ~(qty_c02_q[5] ^ _0023_);
  assign _0178_ = payout_active ? qc02_next[5] : qty_c02_q[5];
  assign _0179_ = _0024_ ? _0178_ : _0177_;
  assign qty_c02_d[5] = _0359_ ? _0179_ : coin[2];
  assign _0180_ = ~(qty_c05_q[5] ^ _0004_);
  assign _0181_ = payout_active ? qc05_next[5] : qty_c05_q[5];
  assign _0182_ = _0005_ ? _0181_ : _0180_;
  assign qty_c05_d[5] = _0427_ ? _0182_ : coin[2];
  assign _0183_ = ~(qty_c10_q[5] ^ _0799_);
  assign _0184_ = payout_active ? qc10_next[5] : qty_c10_q[5];
  assign _0185_ = _0800_ ? _0184_ : _0183_;
  assign qty_c10_d[5] = _0459_ ? _0185_ : coin[2];
  assign _0186_ = ~(credito_q[5] ^ _0780_);
  assign credito_d[5] = _0781_ & _0186_;
  assign _0187_ = disponibile_q[9] & ~(payout_active);
  assign _0188_ = _0610_ & ~(_0573_);
  assign _0189_ = _0187_ | _0188_;
  assign _0190_ = ~(disponibile_q[9] ^ _0479_);
  assign _0191_ = do_add_coin ? _0190_ : _0189_;
  assign _0192_ = ~(_0455_ & _0460_);
  assign _0193_ = ~(disponibile_q[9] ^ _0423_);
  assign _0194_ = ~(_0192_ ^ _0193_);
  assign _0195_ = _0459_ ? _0191_ : _0194_;
  assign _0196_ = _0424_ & _0428_;
  assign _0197_ = ~(disponibile_q[9] ^ _0196_);
  assign _0198_ = _0427_ ? _0195_ : _0197_;
  assign _0199_ = ~(disponibile_q[9] ^ _0638_);
  assign _0200_ = _0359_ ? _0198_ : _0199_;
  assign disponibile_d[9] = _0642_ & _0200_;
  assign _0201_ = ~(errore_q[1] & _0264_);
  assign _0202_ = ~(selezione[2] & _0000_);
  assign _0203_ = ~(do_err & _0202_);
  assign errore_d[1] = ~(_0201_ & _0203_);
  assign _0204_ = ~(resto_q[5] & _0264_);
  assign _0205_ = ~(sel_price[5] & _0267_);
  assign _0206_ = ~(_0204_ & _0205_);
  assign resto_d[5] = payout_active ? _0582_ : _0206_;
  assign _0207_ = do_ok ? c_prod1 : prod1_q;
  assign prod1_d = _0222_ & _0207_;
  assign _0208_ = do_ok ? c_prod2 : prod2_q;
  assign prod2_d = _0222_ & _0208_;
  assign _0209_ = do_ok ? c_prod3 : prod3_q;
  assign prod3_d = _0222_ & _0209_;
  assign _0210_ = do_ok ? c_prod4 : prod4_q;
  assign prod4_d = _0222_ & _0210_;
  assign _0211_ = ~(coin01_q[5] & _0223_);
  assign _0212_ = ~(c01_calc[5] & payout_active);
  assign coin01_d[5] = ~(_0211_ & _0212_);
  assign _0213_ = ~(coin02_q[5] & _0223_);
  assign _0214_ = ~(c02_calc[5] & payout_active);
  assign coin02_d[5] = ~(_0213_ & _0214_);
  assign _0215_ = ~(coin05_q[5] & _0223_);
  assign _0216_ = ~(c05_calc[5] & payout_active);
  assign coin05_d[5] = ~(_0215_ & _0216_);
  assign _0217_ = ~(coin10_q[5] & _0223_);
  assign _0218_ = ~(c10_calc[5] & payout_active);
  assign coin10_d[5] = ~(_0217_ & _0218_);
  (* src = "structural/vending_structural.v:288.21-288.101" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_c01 (
    .D(qty_c01_d),
    .Q(qty_c01_q),
    .clk(clk),
    .enable(we_c01),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:289.21-289.101" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_c02 (
    .D(qty_c02_d),
    .Q(qty_c02_q),
    .clk(clk),
    .enable(we_c02),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:290.21-290.101" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_c05 (
    .D(qty_c05_d),
    .Q(qty_c05_q),
    .clk(clk),
    .enable(we_c05),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:291.21-291.101" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_c10 (
    .D(qty_c10_d),
    .Q(qty_c10_q),
    .clk(clk),
    .enable(we_c10),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:294.21-294.105" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_credito (
    .D(credito_d),
    .Q(credito_q),
    .clk(clk),
    .enable(we_credito),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:295.22-295.117" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000001010  R_disp (
    .D(disponibile_d),
    .Q(disponibile_q),
    .clk(clk),
    .enable(we_disponibile),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:296.22-296.102" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000010  R_err (
    .D(errore_d),
    .Q(errore_q),
    .clk(clk),
    .enable(we_errore),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:302.22-302.104" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_out01 (
    .D(coin01_d),
    .Q(coin01_q),
    .clk(clk),
    .enable(we_coin_out),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:303.22-303.104" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_out02 (
    .D(coin02_d),
    .Q(coin02_q),
    .clk(clk),
    .enable(we_coin_out),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:304.22-304.104" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_out05 (
    .D(coin05_d),
    .Q(coin05_q),
    .clk(clk),
    .enable(we_coin_out),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:305.22-305.104" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_out10 (
    .D(coin10_d),
    .Q(coin10_q),
    .clk(clk),
    .enable(we_coin_out),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:298.22-298.98" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000001  R_p1 (
    .D(prod1_d),
    .Q(prod1_q),
    .clk(clk),
    .enable(we_prod),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:299.22-299.98" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000001  R_p2 (
    .D(prod2_d),
    .Q(prod2_q),
    .clk(clk),
    .enable(we_prod),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:300.22-300.98" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000001  R_p3 (
    .D(prod3_d),
    .Q(prod3_q),
    .clk(clk),
    .enable(we_prod),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:301.22-301.98" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000001  R_p4 (
    .D(prod4_d),
    .Q(prod4_q),
    .clk(clk),
    .enable(we_prod),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:283.21-283.108" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_price_p1 (
    .D(price_p1_d),
    .Q(price_p1_q),
    .clk(clk),
    .enable(init_price_p1),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:284.21-284.108" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_price_p2 (
    .D(price_p2_d),
    .Q(price_p2_q),
    .clk(clk),
    .enable(init_price_p2),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:285.21-285.108" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_price_p3 (
    .D(price_p3_d),
    .Q(price_p3_q),
    .clk(clk),
    .enable(init_price_p3),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:286.21-286.108" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_price_p4 (
    .D(price_p4_d),
    .Q(price_p4_q),
    .clk(clk),
    .enable(init_price_p4),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:278.21-278.102" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_qty_p1 (
    .D(qty_p1_d),
    .Q(qty_p1_q),
    .clk(clk),
    .enable(we_qty_p1),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:279.21-279.102" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_qty_p2 (
    .D(qty_p2_d),
    .Q(qty_p2_q),
    .clk(clk),
    .enable(we_qty_p2),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:280.21-280.102" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_qty_p3 (
    .D(qty_p3_d),
    .Q(qty_p3_q),
    .clk(clk),
    .enable(we_qty_p3),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:281.21-281.102" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_qty_p4 (
    .D(qty_p4_d),
    .Q(qty_p4_q),
    .clk(clk),
    .enable(we_qty_p4),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:297.22-297.99" *)
  \$paramod\RegistroPP\N=s32'00000000000000000000000000000110  R_resto (
    .D(resto_d),
    .Q(resto_q),
    .clk(clk),
    .enable(we_resto),
    .rst(rst)
  );
  (* src = "structural/vending_structural.v:94.24-94.79" *)
  \$paramod\ComparatoreGE\N=s32'00000000000000000000000000000110  cmp_credito (
    .A(credito_q),
    .B(sel_price),
    .O(credito_ge_selprice)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "structural/vending_structural.v:99.17-121.6" *)
  vending_fsm fsm (
    .annulla(annulla),
    .clear_outputs(clear_outputs),
    .clk(clk),
    .coin(coin),
    .conferma(conferma),
    .do_add_coin(do_add_coin),
    .do_cancel(do_cancel),
    .do_erogazione(do_erogazione),
    .do_err(do_err),
    .do_ok(do_ok),
    .init_counter(init_counter_w),
    .is_credito_suff(credito_ge_selprice),
    .is_stock_ok(_0000_),
    .mode_init(mode_init),
    .prodotto1(c_prod1),
    .prodotto2(c_prod2),
    .prodotto3(c_prod3),
    .prodotto4(c_prod4),
    .rst(rst),
    .sel_latched(sel_latched),
    .selezione(selezione)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "structural/vending_structural.v:136.17-151.6" *)
  GreedyLogic greedy_inst (
    .c01_to_emit(c01_calc),
    .c02_to_emit(c02_calc),
    .c05_to_emit(c05_calc),
    .c10_to_emit(c10_calc),
    .change6(payout_amount),
    .do_erogazione(payout_active),
    .qc01_next(qc01_next),
    .qc02_next(qc02_next),
    .qc05_next(qc05_next),
    .qc10_next(qc10_next),
    .qty_c01_curr(qty_c01_q),
    .qty_c02_curr(qty_c02_q),
    .qty_c05_curr(qty_c05_q),
    .qty_c10_curr(qty_c10_q)
  );
  (* src = "structural/vending_structural.v:90.15-90.93" *)
  \$paramod\Mux4\N=s32'00000000000000000000000000000110  mux_price (
    .In0(price_p1_q),
    .In1(price_p2_q),
    .In2(price_p3_q),
    .In3(price_p4_q),
    .O(sel_price),
    .sel(selezione[1:0])
  );
  (* src = "structural/vending_structural.v:91.15-91.91" *)
  \$paramod\Mux4\N=s32'00000000000000000000000000000110  mux_qty (
    .In0(qty_p1_q),
    .In1(qty_p2_q),
    .In2(qty_p3_q),
    .In3(qty_p4_q),
    .O(sel_qty),
    .sel(selezione[1:0])
  );
  assign cfg_value = { coin, selezione };
  assign cfg_value_10 = { 4'h0, coin, selezione };
  assign coin_01 = coin01_q;
  assign coin_02 = coin02_q;
  assign coin_05 = coin05_q;
  assign coin_10 = coin10_q;
  assign coin_value_10[9:6] = 4'h0;
  assign credito = credito_q;
  assign disp_init_c01 = { 4'h0, coin, selezione };
  assign disponibile = disponibile_q;
  assign errore = errore_q;
  assign prodotto1 = prod1_q;
  assign prodotto2 = prod2_q;
  assign prodotto3 = prod3_q;
  assign prodotto4 = prod4_q;
  assign resto = resto_q;
  assign sel_idx = selezione[1:0];
  assign we_current_price = do_ok;
  assign we_price_p1 = init_price_p1;
  assign we_price_p2 = init_price_p2;
  assign we_price_p3 = init_price_p3;
  assign we_price_p4 = init_price_p4;
endmodule
